### ISSUE TITLE
does not include the extension.js 

### ISSUE THREAD

**Issue by satokaz** [DracotMolver/cronos#1]
Hi,

It has not been included extension.

```
$ pwd
/Users/satokaz/.vscode-insiders/extensions/DiegoMolina.Cronos-0.0.1
$ ls -1
README.md
images
node_modules
package.json
```

I think, 'out/**' has been described in the .vscodeignore.

**Comment by DracotMolver** [comment]
Hi @satokaz, Thanks a lot for your feedback, really. I fixed the issues, know is working. :)
